cpp: cpp.c c-ppoutput.c ../input.c ../../libcpp/build/libcpp.a ../../libiberty/build/libiberty.a
	g++ -o cpp -O0 -g3 -save-temps cpp.c c-ppoutput.c ../input.c -I ../../libcpp/include -I .. -I ../../include -I . -I .. ../../libcpp/build/libcpp.a ../../libiberty/build/libiberty.a

#./c-pch.c 
